name: tina-env
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.8  # Updated to CUDA 11.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # PyTorch with CUDA 11.8 support
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytest
  - jupyterlab
  - pip:
      - onnxruntime-gpu
      - onnx
      - tensorboard
      - tqdm
